# update-slides.ps1
# Scans all HTML files under slides/ (excluding _static/) and writes
# slides/_static/slides-data.js — a plain JS file that defines window.SLIDES_DATA.
# Run this script from the project root whenever slides are added or reordered.

$slidesRoot = Join-Path $PSScriptRoot "slides"
$outPath    = Join-Path $slidesRoot "_static\slides-data.js"

# Collect all HTML files outside _static, sorted by relative path
$files = Get-ChildItem -Path $slidesRoot -Recurse -Filter "*.html" |
    Where-Object { $_.FullName -notmatch '\\_static\\' } |
    Sort-Object  { $_.FullName.Substring($slidesRoot.Length + 1) }

# Build JS
$lines = @("// Auto-generated by update-slides.ps1 — do not edit by hand.")
$lines += "window.SLIDES_DATA = ["
$page = 1
foreach ($file in $files) {
    $rel    = $file.FullName.Substring($slidesRoot.Length + 1).Replace("\", "/")
    $comma  = if ($page -lt $files.Count) { "," } else { "" }
    $lines += "    { path: `"$rel`", page: $page }$comma"
    $page++
}
$lines += "];"

# Write JS (UTF-8 without BOM)
[System.IO.File]::WriteAllLines($outPath, $lines, [System.Text.UTF8Encoding]::new($false))

Write-Host "slides-data.js updated - $($files.Count) slides"
foreach ($file in $files) {
    $rel = $file.FullName.Substring($slidesRoot.Length + 1).Replace("\", "/")
    Write-Host "  $rel"
}
