#!/usr/bin/env bash
# update-slides.sh
# Scans all HTML files under slides/ (excluding _static/) and writes
# slides/_static/slides-data.js - a plain JS file that defines window.SLIDES_DATA.
# Run this script from the project root whenever slides are added or reordered.

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
slides_root="$script_dir/slides"
out_path="$slides_root/_static/slides-data.js"

if [[ ! -d "$slides_root" ]]; then
    echo "Error: slides directory not found at $slides_root" >&2
    exit 1
fi

mkdir -p "$(dirname "$out_path")"

# Collect all HTML files outside _static, sorted by relative path.
mapfile -d '' files < <(
    find "$slides_root" -type f -name "*.html" ! -path "$slides_root/_static/*" -print0 | sort -z
)

count=${#files[@]}

{
    echo "// Auto-generated by update-slides.sh - do not edit by hand."
    echo "window.SLIDES_DATA = ["

    page=1
    for file in "${files[@]}"; do
        rel="${file#"$slides_root/"}"
        rel_escaped="${rel//\"/\\\"}"

        comma=""
        if (( page < count )); then
            comma=","
        fi

        printf '    { path: "%s", page: %d }%s\n' "$rel_escaped" "$page" "$comma"
        ((page++))
    done

    echo "];"
} > "$out_path"

echo "slides-data.js updated - $count slides"
for file in "${files[@]}"; do
    rel="${file#"$slides_root/"}"
    echo "  $rel"
done
