// Auto-generated by update-slides.ps1 — do not edit by hand.
window.SLIDES_DATA = [
    { path: "01_intro/01_generic_test_automation_architecture.html", page: 1 },
    { path: "01_intro/02_rf_in_a_nutshell.html", page: 2 },
    { path: "01_intro/03_suite_file.html", page: 3 },
    { path: "01_intro/04_rf_as_top_test_layer.html", page: 4 },
    { path: "02_syntax/01_general_syntax.html", page: 5 },
    { path: "02_syntax/02_keyword_calls.html", page: 6 },
    { path: "02_syntax/03_control_structures.html", page: 7 },
    { path: "02_syntax/04_variables.html", page: 8 },
    { path: "04_architecture/01_file_architecture.html", page: 9 },
    { path: "04_architecture/02_rf_hierarchy.html", page: 10 },
    { path: "04_architecture/03_rf_hierarchy_order_vis.html", page: 11 },
    { path: "04_architecture/04_rf_execution.html", page: 12 },
    { path: "04_architecture/05_rf_result_hierarchy.html", page: 13 }
];
